server:
  port: 8999
  ssl:
    certificate: classpath:ssl2/selft_server.crt
    certificate-private-key: classpath:ssl2/ca_server.key
    #key-store: classpath:ssl/server01.p12
    #key-store-password: changeit
    #key-store-type: PKCS12

channel:
  mtuan:
    url: http://127.0.0.1:8999
    appId: UUU-asd-01
    publicKey: fajdkf9492304jklfahqq