server:
  ssl:
#    certificate: classpath:ssl2/ca_server.crt
#    certificate-private-key: classpath:ssl2/ca_server.key
    key-store: classpath:ssl2/ca_server.p12
    key-store-password: 123abcd
    key-store-type: PKCS12
#    key-alias: item01
    client-auth: need

    enabled-protocols: TLSv1.2
    ciphers: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

#    trust-certificate:  classpath:ssl2/ca_client.crt

#    trust-certificate-private-key: classpath:ssl2/ca_client.key
    trust-store:  classpath:ssl2/ca_client_has_trust.pkcs12
    trust-store-password: 123abc
#    trust-store-type: PKCS12


